"""Application settings management."""

from typing import List, Optional
import os
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    APP_ENV: str = "development"
    APP_NAME: str = "pikol-bknd"
    # postgresql project — DATABASE_URL must be configured explicitly.
    # There is deliberately NO silent SQLite fallback: pointing a postgresql
    # project at a local file database by accident hides misconfiguration.
    DATABASE_URL: str = ""

    @field_validator("DATABASE_URL")
    @classmethod
    def _require_database_url(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError(
                "DATABASE_URL is not set. Open .env (copy from .env.example if "
                "missing) and uncomment/fill the DATABASE_URL line for your "
                "postgresql database before starting the app."
            )
        return v

    # Enforce minimum 32 character length on the JWT secret key
    JWT_SECRET_KEY: str = Field("your-minimum-32-character-secret-key-here", min_length=32)
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    JWT_REFRESH_TOKEN_EXPIRE_DAYS: int = 7

    # CORS Protection — accepts JSON array OR comma-separated string in .env
    # e.g.  ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    # or     ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    ALLOWED_ORIGINS: List[str] = ["http://localhost:3000", "http://localhost:8000"]

    @field_validator("ALLOWED_ORIGINS", mode="before")
    @classmethod
    def parse_allowed_origins(cls, v: object) -> list[str]:
        """Accept both a JSON array string and a plain comma-separated string."""
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            v = v.strip()
            if v.startswith("["):
                import json
                return json.loads(v)
            return [origin.strip() for origin in v.split(",") if origin.strip()]
        return v  # let pydantic handle any other type

    # Rate Limiting settings
    RATE_LIMIT_GET: str = "60/minute"
    RATE_LIMIT_WRITE: str = "20/minute"

    # ── Offline / Online engine (Phase 6, Feature 3 — Layer 1) ────────────────
    # DB_MODE governs which single database is bound at startup:
    #   online  (default) — always DATABASE_URL; fail loudly if unreachable.
    #   offline           — always OFFLINE_DATABASE_URL.
    #   auto              — probe the primary once (2s); fall back to offline.
    DB_MODE: str = "online"
    # Relational models are portable, so the offline mirror is local SQLite.
    OFFLINE_DATABASE_URL: str = "sqlite+aiosqlite:///./.kaira/offline.db"
    # FALLBACK_MODE governs runtime resilience (Layers 2/3). Shipped OFF this
    # phase: no read-only serving, no write queue. Do not enable without the
    # upper layers built — see the Kaira offline guide.
    FALLBACK_MODE: str = "off"

    DEBUG: bool = False

    model_config = SettingsConfigDict(
        # ".env" is the active config (generated by `kaira init`, and what
        # `kaira env switch` copies into place). A profile file like
        # ".env.development" is read first as a lower-priority fallback for
        # multi-env workflows; values in ".env" always win. Missing files are
        # skipped silently.
        env_file=(f".env.{os.getenv('APP_ENV', 'development')}", ".env"),
        env_file_encoding="utf-8",
        extra="ignore"
    )

settings = Settings()